fix some tilelayer error
maptalks/examples pull request #111
Opened 2021-07-17 04:17 UTC by deyihu

2021-07-17 13:18 UTC, fuzhenn requested changes

2021-07-17 13:18 UTC, fuzhenn commented on src/tilelayer-projection/custom-tile/index.js
> +function resolutionToScale(resolution, dpi, mapUnit) {
这个例子的注释需要改成英文的

2021-07-17 13:46 UTC, deyihu commented on src/tilelayer-projection/custom-tile/index.js
> +function resolutionToScale(resolution, dpi, mapUnit) {
嗯嗯

2021-07-19 08:28 UTC, fuzhenn approved these changes

2021-07-19 08:32 UTC, fuzhenn requested changes

2021-07-19 08:32 UTC, fuzhenn commented on src/tilelayer-projection/custom-tile/index.js
> +  center: [39.79, 116.85].reverse(),
这个reverse有点别扭，改回 [116.85, 39.79]吧

2021-07-19 08:32 UTC, fuzhenn commented on src/tilelayer-projection/custom-tile/index.js
> +  var crs = this.getMap().getSpatialReference()._projection;
示例里不宜出现内部变量的访问方式

this.getMap().getSpatialReference()._projection;

改为：

this.getMap().getSpatialReference().getProjection()

2021-07-19 08:35 UTC, fuzhenn requested changes

2021-07-19 08:35 UTC, fuzhenn commented on src/tilelayer-projection/epsg4326/index.js
> +    // new maptalks.TileLayer('road', {
示例里不宜出现注释代码，应该删除掉

2021-08-03 03:36 UTC, fuzhenn approved these changes

2021-08-03 03:36 UTC, merged